export const queryKeys = {
	profile: ["profile"],
	workspaces: ["workspaces"],
	incomingInvites: ["invites", "incoming"],
	friends: (q?: string) => ["friends", q ?? ""],
	friendRequestsIncoming: ["friends", "requests", "incoming"],
	friendRequestsOutgoing: ["friends", "requests", "outgoing"],
	channels: (workspaceId?: string | null) => ["channels", workspaceId],
	threadsList: (workspaceId?: string | null) => ["threads", "list", workspaceId ?? ""],
	threadsRecent: (workspaceId?: string | null, q?: string) => ["threads", "recent", workspaceId ?? "", q ?? ""],
	channelMessages: (channelId?: string | null) => ["channels", channelId, "messages"],
	threadMessages: (threadId?: string | null) => ["threads", threadId, "messages"],
	presence: (channelId?: string | null) => ["channels", channelId, "presence"],
	sessions: ["sessions"],
};
